
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 10 00:18:21 CET 2016
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 25;
  public static final int CONST = 3;
  public static final int EQUALS = 5;
  public static final int STRCONST = 43;
  public static final int GREATER = 36;
  public static final int LPAREN = 16;
  public static final int SEMI = 21;
  public static final int LESS = 33;
  public static final int MINUS = 22;
  public static final int RPAREN = 17;
  public static final int AND = 32;
  public static final int LESSEQUAL = 35;
  public static final int OR = 39;
  public static final int COMMA = 20;
  public static final int CLASS = 27;
  public static final int DIV = 29;
  public static final int PLUS = 23;
  public static final int IF = 8;
  public static final int LSQBRACE = 18;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 24;
  public static final int RETURN = 12;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int ISEQUAL = 26;
  public static final int PROGRAM = 13;
  public static final int MUL = 34;
  public static final int NUMBER = 40;
  public static final int MOD = 30;
  public static final int IDENT = 42;
  public static final int BREAK = 11;
  public static final int VOID = 4;
  public static final int GREATEREQUAL = 31;
  public static final int ISNOTEQUAL = 37;
  public static final int LBRACE = 14;
  public static final int ELSE = 9;
  public static final int POINT = 38;
  public static final int READ = 6;
  public static final int CHARCONST = 41;
  public static final int WHILE = 10;
  public static final int RBRACE = 15;
  public static final int BOOLCONST = 44;
  public static final int EXTENDS = 2;
  public static final int RSQBRACE = 19;
  public static final int PRINT = 7;
}

